reasoning_gym_resources_server:
  resources_servers:
    reasoning_gym:
      entrypoint: app.py
      domain: reasoning

reasoning_gym_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: reasoning_gym_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: example
        type: example
        jsonl_fpath: resources_servers/reasoning_gym/data/example.jsonl
        num_repeats: 1
