textworld_resources_server:
  resources_servers:
    textworld:
      entrypoint: app.py
      expose_admissible_commands: false 
textworld_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      max_steps: 15
      resources_server:
        type: resources_servers
        name: textworld_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: example
        type: example
        jsonl_fpath: resources_servers/textworld/data/example.jsonl
        num_repeats: 1
