policy_model:
  responses_api_models:
    vllm_model:
      entrypoint: app.py
      base_url: http://0.0.0.0:8000
      api_key: "filler"
      model: Qwen/Qwen3-30B-A3B
      return_token_id_information: false
      uses_reasoning_parser: true
