my_gpt4p1_simple_chat_agent:  # This is the name of your server and will be used to identify it in subsequent requests.
  responses_api_agents:  # This is the server type. There are 3 server types: Responses API agent, Responses API model, and Resource servers
    simple_chat_agent:  # This is the agent type. This is custom and written by you.
      entrypoint: app.py  # This is the server entrypoint path, relative to the agent type folder.
      openai_base_url: https://api.openai.com/v1
      openai_api_key: ???
      openai_model_name: gpt-4.1-2025-04-14
